name: build-images

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 11 * * *'

jobs:
  build-images:
    concurrency:
      group: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Show available platforms
        run: docker buildx ls
      - 
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx
      -
        name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Setup Python Env
        uses: actions/setup-python@v4
        with:
            python-version: '3.8'
      - name: Run Build Script
        run: |
          pip install -r requirements.txt
          python -u run.py
      - name: Commit database file
        uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: Learner's Block
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Update database files'
          branch: main
          add: '*.json'
